# Website Traffic Forecasting

In [4]:
import os
os.getcwd()

'C:\\Users\\PC'

In [5]:
os.chdir(r"D:\FQL\PJ 4")

### Section 1 : Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns
import warnings, os
warnings.filterwarnings('ignore')

In [2]:
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [3]:
plt.rcParams.update({'figure.dpi': 120, 'axes.spines.top': False, 'axes.spines.right': False})
C = dict(blue='#1D4ED8', green='#15803D', red='#B91C1C', amber='#B45309', slate='#475569')
os.makedirs('data', exist_ok=True)
os.makedirs('plots', exist_ok=True)
NUM_COLS = ['Page_Loads', 'Unique_Visits', 'First_Time_Visits', 'Returning_Visits']
print('All libraries loaded.')

All libraries loaded.

### Section 2 : Load Data

In [6]:
RAW_PATH = 'daily-website-visitors.csv'
df_raw = pd.read_csv(RAW_PATH)
print(f'Shape : {df_raw.shape}')
print(f'Columns: {df_raw.columns.tolist()}')

Shape : (2167, 8)
Columns: ['Row', 'Day', 'Day.Of.Week', 'Date', 'Page.Loads', 'Unique.Visits', 'First.Time.Visits', 'Returning.Visits']

In [7]:
df_raw.head(8)

,Row,Day,Day.Of.Week,Date,Page.Loads,Unique.Visits,First.Time.Visits,Returning.Visits
0,1,Sunday,1,9/14/2014,"2,146","1,582","1,430",152
1,2,Monday,2,9/15/2014,"3,621","2,528","2,297",231
2,3,Tuesday,3,9/16/2014,"3,698","2,630","2,352",278
3,4,Wednesday,4,9/17/2014,"3,667","2,614","2,327",287
4,5,Thursday,5,9/18/2014,"3,316","2,366","2,130",236
5,6,Friday,6,9/19/2014,"2,815","1,863","1,622",241
6,7,Saturday,7,9/20/2014,"1,658","1,118",985,133
7,8,Sunday,1,9/21/2014,"2,288","1,656","1,481",175

### Section 3: Data Quality Report

In [8]:
report = pd.DataFrame({
    'dtype':   df_raw.dtypes,
    'nulls':   df_raw.isnull().sum(),
    'null_%':  (df_raw.isnull().mean()*100).round(2),
    'unique':  df_raw.nunique(),
})

In [10]:
print('======= Quality Report =======')
display(report)
print(f'Duplicate rows: {df_raw.duplicated().sum()}')

======= Quality Report =======

                    dtype  nulls  null_%  unique
Row                 int64      0     0.0    2167
Day                object      0     0.0       7
Day.Of.Week         int64      0     0.0       7
Date               object      0     0.0    2167
Page.Loads         object      0     0.0    1756
Unique.Visits      object      0     0.0    1658
First.Time.Visits  object      0     0.0    1587
Returning.Visits   object      0     0.0     663

Duplicate rows: 0

In [11]:
print('\nDescriptive Stats:')
df_raw.describe()

Descriptive Stats:

               Row  Day.Of.Week
count  2167.000000  2167.000000
mean   1084.000000     3.997231
std     625.703338     2.000229
min       1.000000     1.000000
25%     542.500000     2.000000
50%    1084.000000     4.000000
75%    1625.500000     6.000000
max    2167.000000     7.000000